# NUMPY

In [ ]:
import numpy as np

## To Store an array

In [ ]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


## dimension of array

In [ ]:
print(a.shape)

(5,)


In [ ]:
b = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
print(b)
print(type(b))
print(b.shape)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
<class 'numpy.ndarray'>
(10, 1)


In [ ]:
c = np.array([[1, 2, 3],[4, 5, 6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


## Creating zeros, ones, and custom arrays

In [ ]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


## Arrays of some constant

In [ ]:
c = np.full((3,2),5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [ ]:
c = np.full((5,10),74)
print(c)

[[74 74 74 74 74 74 74 74 74 74]
 [74 74 74 74 74 74 74 74 74 74]
 [74 74 74 74 74 74 74 74 74 74]
 [74 74 74 74 74 74 74 74 74 74]
 [74 74 74 74 74 74 74 74 74 74]]


## Identity Matrix - Square Matrix

In [ ]:
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Random Matrix

In [ ]:
randomMatrix = np.random.random((2,3))
print(randomMatrix)

[[0.40383344 0.94378628 0.20987822]
 [0.15330606 0.07233951 0.94067354]]


In [ ]:
# 1st Column Matrix
print(randomMatrix[:,1])

[0.94378628 0.07233951]


In [ ]:
# 2nd Column Matrix
print(randomMatrix[:,2])

[0.20987822 0.94067354]


In [ ]:
# 0th ROW Matrix
print(randomMatrix[0,:])

[0.40383344 0.94378628 0.20987822]


In [ ]:
#changing rth row column index starting from i to j [r, i:j]
randomMatrix[1,1:]=1
print(randomMatrix)

[[0.40383344 0.94378628 0.20987822]
 [0.15330606 1.         1.        ]]


In [ ]:
#changing cth column row index starting from i to j [i:j,c ]
randomMatrix[0:2,0]=1
print(randomMatrix)

[[1.         0.94378628 0.20987822]
 [1.         1.         1.        ]]


## Setting Rows and Columns with any values

In [ ]:
sc = np.zeros((5,5))
print(sc)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Changing Row elements
sc[1,:] = 21
print(sc)

[[ 0.  0.  0.  0.  0.]
 [21. 21. 21. 21. 21.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [ ]:
# Changing Column elements
sc[:,2] = 74
print(sc)

[[ 0.  0. 74.  0.  0.]
 [21. 21. 74. 21. 21.]
 [ 0.  0. 74.  0.  0.]
 [ 0.  0. 74.  0.  0.]
 [ 0.  0. 74.  0.  0.]]


In [ ]:
# changing last column
sc[:,-1] = 30
print(sc)

[[ 0.  0. 74.  0. 30.]
 [21. 21. 74. 21. 30.]
 [ 0.  0. 74.  0. 30.]
 [ 0.  0. 74.  0. 30.]
 [ 0.  0. 74.  0. 30.]]


In [ ]:
# changing last row
sc[-1, :] = 30
print(sc)

[[ 0.  0. 74.  0. 30.]
 [21. 21. 74. 21. 30.]
 [ 0.  0. 74.  0. 30.]
 [ 0.  0. 74.  0. 30.]
 [30. 30. 30. 30. 30.]]


## Datatypes

In [ ]:
sr = np.zeros((7,7))
print(sr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
sr = np.zeros((7,7),dtype = np.int64)
print(sr)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [ ]:
sr[1,:] = 74
sr[:,-1] = 21

In [ ]:
print(sr)

[[ 0  0  0  0  0  0 21]
 [74 74 74 74 74 74 21]
 [ 0  0  0  0  0  0 21]
 [ 0  0  0  0  0  0 21]
 [ 0  0  0  0  0  0 21]
 [ 0  0  0  0  0  0 21]
 [ 0  0  0  0  0  0 21]]


## Mathematical Operations

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [ ]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


### Elementwise operations
- Addition 
- Subtraction
- Multiplication
- Division
- SquareRoot

In [ ]:
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [ ]:
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [ ]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [ ]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
print(np.sqrt(y))

[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


### Matrix Multiplication/ Dot Product

In [ ]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
print(a.dot(b))


55


In [ ]:
print(a)

[1 2 3 4 5]


In [ ]:
# print all the elements sum
print(sum(a))
print(np.sum(a))

15
15


Axis = 0 => operation along column
Axis = 1 => operation along row 

In [ ]:
print(x)

[[1 2]
 [3 4]]


In [ ]:
print(np.sum(x, axis = 0))

[4 6]


In [ ]:
print(np.sum(x, axis = 1))

[3 7]


## Stacking of Arrays

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [ ]:
print(a)

[1 2 3 4 5]


In [ ]:
print(b)

[ 6  7  8  9 10]


In [ ]:
b = b**2
print(b)

[ 36  49  64  81 100]


In [ ]:
np.stack((a,b),axis = 1)

array([[  1,  36],
       [  2,  49],
       [  3,  64],
       [  4,  81],
       [  5, 100]])

In [ ]:
np.stack((a,b),axis = 0)

array([[  1,   2,   3,   4,   5],
       [ 36,  49,  64,  81, 100]])

## Reshaping Array

In [ ]:
a=np.stack((a,b), axis=0)
print(a)
a = a.reshape((5,2))
print(a)

[[  1   2   3   4   5]
 [ 36  49  64  81 100]]
[[  1   2]
 [  3   4]
 [  5  36]
 [ 49  64]
 [ 81 100]]


In [ ]:
a = a.reshape((1,10))
print(a)

[[  1   2   3   4   5  36  49  64  81 100]]


In [ ]:
a = a.reshape((10,1))
print(a)

[[  1]
 [  2]
 [  3]
 [  4]
 [  5]
 [ 36]
 [ 49]
 [ 64]
 [ 81]
 [100]]


In [ ]:
# Automatically column will be detected
a.reshape((2,-1))

array([[  1,   2,   3,   4,   5],
       [ 36,  49,  64,  81, 100]])

In [ ]:
# Automatically row will be detected
a.reshape((-1,2))

array([[  1,   2],
       [  3,   4],
       [  5,  36],
       [ 49,  64],
       [ 81, 100]])

## Python - Random Generators Numpy

- rand
- randn
- randint
- random
- choice
- suffle

In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [ ]:
np.random.seed(1) # Seed is use to store the random number generated for future use
np.random.shuffle(a)
print(a)

[9 7 7]


In [ ]:
# Generate arrays of random Numbers

a =np.random.rand(2, 3)
print(a)

[[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]


In [ ]:
# Return values from a standard normal distributions

a =np.random.randn(2, 3)
print(a)


[[-1.10593508 -1.65451545 -2.3634686 ]
 [ 1.13534535 -1.01701414  0.63736181]]


In [ ]:
# (start,final,NoOfValues) -> [start,final)
a = np.random.randint(5,10,3)
print(a)

[7 9 7]


In [ ]:
# Randomly Picking one elements from a array

element = np.random.choice([1,4,5,3,21,74])
print(element)

21


## Statical Computation using Numpy

- min/max
- mean
- median
- average
- variance
- standard deviation



In [ ]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [ ]:
#min/ max
print(np.min(a))
print(np.max(a))

0
7


In [ ]:
print(np.min(a,axis=0))
print(np.max(a,axis=0))

[1 2 2 0]
[7 6 3 4]


In [ ]:
print(np.min(a,axis=1))
print(np.max(a,axis=1))

[1 0]
[4 7]


In [ ]:
# mean
b = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
m=sum(b)/10
print(m)
print(np.mean(b))

5.5
5.5


In [ ]:
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [ ]:
# coulumn
print(np.mean(a,axis=0))
# row
print(np.mean(a,axis=1))

[4.  4.  2.5 2. ]
[2.5  3.75]


In [ ]:
c= np.array([1,5,4,2,0])

In [ ]:
print(np.median(c))

2.0


In [ ]:
# Average
v= np.array([1,5,4,2,0])
w = np.array([1,2,3,4,5])
print(np.average(v, weights=w))

2.066666666666667


In [ ]:
# Standard Deviation
dev = np.std(v)
print(dev)

1.854723699099141


In [ ]:
print(np.var(v))

3.4400000000000004


In [ ]:
 # https://www.youtube.com/playlist?list=PLz8TdOA7NTzSu-ePbGtghroiomWA-FFK9